name: Build & Push Core images

'on': [push]
#  release:
#    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the tagged Docker image
        run: docker-compose -f compose/core-4.0.4.yml build
      - name: Push the tagged Docker image
        run: docker-compose  -f compose/core-4.0.4.yml push
